"""
Portfolio Calendar Pull — app logo generator.

Original work. The mark is built entirely from primitive geometry (rounded
rectangles, a rectangle and a triangle) generated by this script. No stock art,
no traced third-party icon, no font glyphs, no external assets. Re-running this
script reproduces the logo exactly.

Usage:  python3 brand/make_logo.py
"""

from PIL import Image, ImageDraw

SS = 4                      # supersampling factor for smooth edges
BASE = 512                  # master size
S = BASE * SS

TOP = (0x5B, 0x7C, 0xFF)    # gradient top    #5B7CFF
BOTTOM = (0x1E, 0x2F, 0xA8) # gradient bottom #1E2FA8
INK = (0xFF, 0xFF, 0xFF)    # foreground


def scaled(*vals):
    """Convert 0..1000 design units to pixels."""
    return [v * S / 1000 for v in vals]


def gradient_square():
    """Vertical linear gradient, clipped to a rounded square."""
    grad = Image.new("RGB", (1, S))
    for y in range(S):
        t = y / (S - 1)
        grad.putpixel((0, y), tuple(
            round(TOP[i] + (BOTTOM[i] - TOP[i]) * t) for i in range(3)
        ))
    grad = grad.resize((S, S))

    mask = Image.new("L", (S, S), 0)
    ImageDraw.Draw(mask).rounded_rectangle(
        [0, 0, S - 1, S - 1], radius=S * 0.225, fill=255
    )

    out = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    out.paste(grad, (0, 0), mask)
    return out


def draw_mark(img):
    """Calendar frame with a downward 'pull' arrow inside."""
    d = ImageDraw.Draw(img)
    stroke = round(S * 0.055)

    # Two hanging tabs above the calendar body
    for cx in (355, 645):
        x0, y0, x1, y1 = scaled(cx - 30, 168, cx + 30, 292)
        d.rounded_rectangle([x0, y0, x1, y1], radius=S * 0.030, fill=INK)

    # Calendar body outline
    bx0, by0, bx1, by1 = scaled(205, 235, 795, 830)
    d.rounded_rectangle(
        [bx0, by0, bx1, by1], radius=S * 0.075, outline=INK, width=stroke
    )

    # Solid header band, squared off at the bottom edge
    hx0, hy0, hx1, hy1 = scaled(205, 235, 795, 400)
    d.rounded_rectangle([hx0, hy0, hx1, hy1], radius=S * 0.075, fill=INK)
    fx0, fy0, fx1, fy1 = scaled(205, 330, 795, 400)
    d.rectangle([fx0, fy0, fx1, fy1], fill=INK)

    # Arrow stem
    sx0, sy0, sx1, sy1 = scaled(470, 480, 530, 655)
    d.rectangle([sx0, sy0, sx1, sy1], fill=INK)

    # Arrow head
    ax, ay = scaled(500, 745)
    lx, ly = scaled(383, 615)
    rx, ry = scaled(617, 615)
    d.polygon([(lx, ly), (rx, ry), (ax, ay)], fill=INK)

    return img


def build():
    img = draw_mark(gradient_square())

    out = {}
    for size in (512, 240, 120, 64, 32):
        out[size] = img.resize((size, size), Image.LANCZOS)
    return out


if __name__ == "__main__":
    import os

    here = os.path.dirname(os.path.abspath(__file__))
    root = os.path.dirname(here)
    imgs = build()

    imgs[512].save(os.path.join(here, "logo-512.png"), optimize=True)
    imgs[240].save(os.path.join(here, "logo-240.png"), optimize=True)
    imgs[120].save(os.path.join(here, "logo-120.png"), optimize=True)

    # Copies served by the website
    imgs[240].save(os.path.join(root, "docs", "logo.png"), optimize=True)
    imgs[32].save(os.path.join(root, "docs", "favicon.png"), optimize=True)

    for f in ("brand/logo-512.png", "brand/logo-240.png", "brand/logo-120.png",
              "docs/logo.png", "docs/favicon.png"):
        p = os.path.join(root, f)
        print(f"{f:26} {os.path.getsize(p):>7,} bytes")
